name: Sync Discussion

on:
  discussion:
    type:
      - create
      - edited
      - labeled
      - locked
      - unlocked

permissions: write-all

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run Python script
        run: |
          python ./.github/scripts/sync.py

      - name: Stage changes
        run: |
          git add .

      - name: Commit changes
        id: commit
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "没有检测到代码变更，跳过提交"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            git config user.name "秃头灯笼鱼"
            git config user.email "ttdlyu@163.com"
            git commit -m "Auto commit: $(date +'%Y-%m-%d %H:%M:%S')" -a
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Push changes
        if: steps.commit.outputs.has_changes == 'true'
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
